# Generated by Django 5.0.2 on 2024-04-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req_date', models.CharField(max_length=50)),
                ('fromdate', models.CharField(max_length=50)),
                ('todate', models.CharField(max_length=50)),
                ('no_of_days', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('leave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.leave_master')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff')),
            ],
            options={
                'db_table': 'Leave3',
            },
        ),
    ]
