# Generated by Django 5.0.2 on 2024-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_leave3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='excel')),
            ],
            options={
                'db_table': 'Attendance_File',
            },
        ),
    ]
