# Generated by Django 5.0.2 on 2024-04-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_attendance_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='month',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='no_of_working_days',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
    ]
