# Generated by Django 5.0.2 on 2024-04-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='product',
            new_name='product_id',
        ),
    ]
