# Generated by Django 5.0.2 on 2024-04-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_product_production_product_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='production',
            table='Production',
        ),
    ]
