# Generated by Django 5.0.2 on 2024-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_production_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_master',
            name='ins_status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
