# Generated by Django 5.0.2 on 2024-04-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_unit_order_c_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_order',
            name='cancel_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
