# Generated by Django 5.0.2 on 2024-05-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_order',
            name='contact_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='unit_order',
            name='vehicle_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
