# Generated by Django 5.0.2 on 2024-05-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_unit_order_contact_number_unit_order_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='aadhar',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_account_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_ifsc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='nation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
