# Generated by Django 5.0.2 on 2024-05-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_staff_aadhar_staff_bank_account_no_staff_bank_ifsc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='staff',
            name='house_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='pin',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='place',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='state',
            field=models.CharField(default='', max_length=150),
        ),
    ]
