# Generated by Django 5.0.2 on 2024-05-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_address_staff_city_staff_house_name_staff_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave3',
            name='certificate',
            field=models.CharField(default='', max_length=250),
        ),
    ]
